### PR TITLE
Feedback frontend

### PR DESCRIPTION
**Pull request by jakobw**
This is the frontend for https://phabricator.wikimedia.org/T111191 as mentioned in #94.

### CODE REVIEW

**Comment by addshore** [comment]
jquery-2.1.4.min.js:4 POST http://tools.wmflabs.org/addshore-dev/ag/feedback_frontend/backend/web/feedback 404 (Not Found)

tools.addshore-dev@tools-bastion-01:~/public_html/ag/feedback_frontend/backend/web$ ls
index.php

**Comment by jakobw** [comment]
Does `mod_rewrite` not work on tool labs? The .htaccess should redirect this :/

**Comment by KaiNissen** [comment]
afaik, labs uses lighttpd. rewrite rules need to go into `~/.lighttpd.conf`.

**Comment by jakobw** [comment]
Ok, who needs pretty URLs anyway.
@addshore Should work now (after clearing the cache)! :)

**Pull request merged**
