### PR TITLE
Scroll parallax

### PR DESCRIPTION
**Pull request by jakobw**
Task on Phab: https://phabricator.wikimedia.org/T111187

This adds parallax scrolling effects to the start screen elements.
I rewrote most of the previous scrolling effects to use only two `ScrollMagic.Scene`s - one for scrolling up and one for scrolling down.

### CODE REVIEW

**Comment by jakobw** [comment]
Demo: http://tools.wmflabs.org/addshore-dev/ag/scroll_parallax/redesign/

**Comment by addshore** [comment]
There is an odd jump for me in Chrome testing this.
When first starting to scroll down the input box jumps down 20 pixels or so before starting to smoothly scroll!!! :/

**Comment by jakobw** [comment]
@addshore I may have fixed it!

**Comment by addshore** [comment]
There still seems to be a jump there for me.
Does it not happen for you?

**Pull request merged**
