### PR TITLE
Change texts.

### PR DESCRIPTION
**Pull request by jakobw**
Task: https://phabricator.wikimedia.org/T122798

### CODE REVIEW

**Comment by WMDE-Fisch** [comment]
Is
>The whole "Verbindung zum Rechteinhaber" should be omitted for licenses 1.0 and 2.0.

Also covered here?

**Comment by jakobw** [comment]
I may be wrong but I don't think that was ever broken. Just the text needed to be replaced. Checking!

**Comment by jakobw** [comment]
I tried some 1.0 and 2.0 licences and it works as advertized. I think the task description is just confusing :)

**Comment by WMDE-Fisch** [comment]
Then moerge!

**Pull request merged**
