### PR TITLE
Add static front page for the redesign.

### PR DESCRIPTION
**Pull request by jakobw**
Task on Phab: https://phabricator.wikimedia.org/T111185

I tested it on Firefox, Chrome and Safari (all on Mac OS) so far.

### CODE REVIEW

**Comment by wmde-manicki** [comment]
I have glanced at it with Firefox and Chromium on Ubuntu and looks really nice. I really like the way the background picture is scaled according to the window size, that it is not being unnecessarily stretched etc. Nice work!
Could not find Internet Explorer version for Linux, so I cannot say how it looks there.

**Comment by addshore** [comment]
Tested on IE11, Chrome & Firefox on Windows 7, Generally looks good.

In Chrome the placeholder text in the box look like this
image
In firefox it is very light
image

**Comment by jakobw** [comment]
@addshore It seems like Chrome has a default placeholder color while Firefox sets the placeholder color depending on the color of the input field. Since the color in the design mockup is already very light, the placeholder color in Firefox is very very light :D
Apparently it can be styled with the `:-moz-placeholder` pseudo class though. Should I make it darker?

**Comment by addshore** [comment]
A little bit darker would be lovely and then I guess I should merge this! :)

**Comment by jakobw** [comment]
Done!

**Pull request merged**
