### PR TITLE
Add all the texts

### PR DESCRIPTION
**Pull request by wmde-manicki**
Task: https://phabricator.wikimedia.org/T116583
Demo: https://tools.wmflabs.org/file-reuse-test/add-all-the-texts/redesign/

I have been copying texts from phabricator task, so hopefully I haven't messed anything up.

Few remarks:
 - "info box" regarding private use will be added in the separate change, so text defined for this part are not included here (ie. title of this PR is a lie),
 - links in the Impressum box were hardly visible when they were white/grey, so I've made them standard blue. If different shade of blue (or grey) is needed, please provide the specs,
 - links open in the new window. I'll change that if it's not intended,
 - text for the "Bearbeitung" question mark has been defined in two places, I've chosen the latter one,
 - same as above for the "Veränderung" question mark text.

### CODE REVIEW

**Comment by wmde-manicki** [comment]
And one more comment: I have not changed the email address that the feedback form would use. I think this should be done once the tool is deployed and so on. Or is the current version deployed somewhere already apart from Adam's awesome test server?

**Comment by addshore** [comment]
It's all just deployed on the awesome test server for now :)

**Comment by JeroenDeDauw** [comment]
-1. these are not ALL the texts

**Comment by JeroenDeDauw** [comment]
> -1. these are not ALL the texts

borded

**Pull request merged**
