### PR TITLE
Use local copy of CC logo

### PR DESCRIPTION
**Pull request by wmde-manicki**
Demo: https://tools.wmflabs.org/file-reuse-test/cc-logo-https/redesign/

Browser shows warning about the insecure content at the final screen of dialogue (CC icon).

### CODE REVIEW

**Comment by addshore** [comment]
Following this URL I get

image

**Comment by wmde-manicki** [comment]
Silly me. But it would not show warnings about the insecure content :) I'll fix it properly

**Comment by wmde-manicki** [comment]
I've looked actually at the logo instead of simply changing `http` to `https` in the URL and it turned out that the logo we used is offered to download and use on own things. So I've downloaded it and put to the repo.

**Comment by jakobw** [comment]
Works now, thanks! :)

**Comment by addshore** [comment]
Epic!

**Pull request merged**
