### PR TITLE
Justify images in a fancy way.

### PR DESCRIPTION
**Pull request by jakobw**
Fancy image justification!
Task on Phab: https://phabricator.wikimedia.org/T111195
Demo: http://tools.wmflabs.org/addshore-dev/ag/fancy_picture_arrangement/redesign/
Instructions: Enter `https://de.wikipedia.org/wiki/Eichhörnchen` and see justified pictures of squirrels!

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
great justice

**Comment by addshore** [comment]
Justify!

**Comment by addshore** [comment]
*makes a note that currently if you click the button twice you'll get the images twice*

**Comment by JeroenDeDauw** [comment]
> Justify!

haha

**Pull request merged**
