### PR TITLE
changed back functionality of button

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
Use browser back and avoid strange errors mixing button- and browser-back.

When testing it seems to work fine for me. Can you give examples where the other version failed @wmde-manicki or @KaiNissen ?

### CODE REVIEW

**Comment by jakobw** [comment]
I get an error `TypeError: Cannot read property 'clone' of undefined` when I click something in the questionnaire, then go back, click something again and then attempt to go forward. I assume it would help to erase the forward history whenever an answer in the questionnaire is selected.

**Comment by WMDE-Fisch** [comment]
The forward history will already be erased when choosing a _new_ path. The problem seems to occur when choosing the _same_ path again.

**Comment by WMDE-Fisch** [comment]
fixed forward history - can now be merge into the history-back-forward-dojo branch 
@jakob-WMDE @KaiNissen

**Comment by wmde-manicki** [comment]
Nice improvements, thanks!

I have just rewritten a little part of `_goTo` function to make it more simple and general, hope you don't mind. And I have also added a little fix for special edge case (clicking forward button on file selection page should also clear forward history).

**Pull request merged**
