### PR TITLE
Improve attribution copying

### PR DESCRIPTION
**Pull request by jakobw**
Task: https://phabricator.wikimedia.org/T106011
This one uses flash but works with Firefox, Safari and Chrome without any issues for me.
Demo: http://tools.wmflabs.org/file-reuse-test/copy_button/redesign/

### CODE REVIEW

**Comment by wmde-manicki** [comment]
Works fine on Ubuntu (FF and Chromium) too. In Chromium copied text gets some extra whitespace (line break + tabs) but I guess this is related to this particular browser.

**Comment by addshore** [comment]
So tested on Win7 with Opera, Chrome, IE11 and FF.

It doesn't work at all with IE11 or Opera for me
I don't get this extra whitespace issue with Chrome

The old one works on Opera and IE11 for me.
But I have the whitespace issue with the old one.

It looks like the best solution would be a mixture of the two? >.>

**Comment by tobijat** [comment]
So if this is based on Flash, what happens on IPhones and IPads? They don't have Flash AFAIK.

**Comment by jakobw** [comment]
Updated with some checks for what's supported.
It will now copy things to the clipboard right away (just IE) if it's supported.
Else it'll use execCommand if it's supported (latest browsers but some with weird behavior).
Else it'll use flash if it's available.
If all those fail it'll hide the button.

I tested this on Firefox (execCommand works!), Safari (uses Flash), Chrome (also uses Flash for some reason), mobile Safari (button is not shown) and MS Edge on Windows 10.

**Comment by wmde-manicki** [comment]
Awesome work!
Tested on Ubuntu+FF/Chromium and worked well.

**Comment by addshore** [comment]
Working in IE and Chrome
Opera I get no copy link
FF does odd things...

**Comment by jakobw** [comment]
Aaaand another update.
It will now

1. Use IE copying if it's IE
2. Use Flash (`ZeroClipboard`) if it's activated and installed
3. Use Clipboard.js (the library we initially used) which will either copy directly or mark the text automatically and ask the user to copy manually (in Safari).
screen shot 2015-12-11 at 18 52 28

I think this should now work in most browsers and doesn't use any strange textarea hacks anymore. I checked Chrome, Safari and FF on OS X and Chrome, FF and Edge on Win10.
Poke @addshore

**Comment by addshore** [comment]
Just tested in IE, Chrome Opera and FF on WIN7 and it works for all perfectly :)
+1

**Comment by wmde-manicki** [comment]
And it also worked for me (FF and Chromium on Ubuntu). Awesome!

**Pull request merged**
